name: Android Github Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  android-detekt:
    name: Android Detekt
    runs-on: ubuntu-latest
    
    steps:    
      - name: Android Detekt
        uses: natiginfo/action-detekt-all@1.22.0
     
  test:
    needs: [android-detekt]
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Run Unit tests
        run: bash ./gradlew testDebugUnitTest

  test_report:
    needs: [test]
    name: Unit TestsCoverage
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
